label: Layout
type: layout
fieldsets:
  basis:
    label: Basis Elemente
    type: group
    fieldsets:
      - heading
      - text
      - list
      - image
      - divider
      - iconflex
      - countup
      - form
      - overlay
      - card
      - table
      - social_icons
      - menu_horizontal
      - menu_vertikal
  groups:
    label: Gruppen Elemente
    type: group
    fieldsets:
      #- imageslider
      #- panels
      #- overlays
      #- images
      - buttons
      - accordion
      - tab
  prestyle:
    extends: fields/sections

layouts:
  - 1/1
  - 1/2, 1/2
  - 1/2, 1/2, 1/2, 1/2
  - 1/1, 1/2, 1/2
  - 1/3, 1/3, 1/3
  - 1/3, 1/3, 1/3, 1/3, 1/3, 1/3
  - 1/1, 1/3, 1/3, 1/3
  - 1/3, 2/3
  - 1/1, 1/3, 2/3
  - 2/3, 1/3
  - 1/1, 2/3, 1/3
  - 1/4, 1/4, 1/4, 1/4
  - 1/4, 3/4
  - 1/1, 1/4, 1/4, 1/4, 1/4
  - 1/2, 1/2, 1/4, 1/4, 1/4, 1/4
  - 1/5, 1/5, 1/5, 1/5, 1/5
  - 1/1, 1/5, 1/5, 1/5, 1/5, 1/5
  - 1/2, 1/2, 1/5, 1/5, 1/5, 1/5, 1/5

settings:
  fields:
    sectionId:
      type: text
      width: 1/2
      help: Interne ID der Section, z. B. für Ankerlinks oder gezielte CSS-Anpassungen
    class:
      type: text
      width: 1/2
      help: Zusätzliche CSS-Klassen zur individuellen Gestaltung
    sectioncolor:
      type: select
      label: Section Farbe
      width: 1/2
      options:
        uk-section-primary: primary
        uk-section-secondary: secondary
        uk-section-muted: muted
      help: Bestimmt die Farbstimmung bzw. Hintergrundfarbe des Abschnitts
    sectionsize:
      type: select
      label: Section Padding
      width: 1/2
      options:
        uk-section-xsmall: xsmall
        uk-section-small: small
        uk-section-large: large
        uk-section-xlarge: xlarge
        vh: VH
      help: Definiert die vertikale Innenabstände (Padding) der Section
    sectionvh:
      width: 1/3
      type: range
      label: %
      min: 1
      max: 100
      when:
        sectionsize: vh
      help: Höhe des Abschnitts in Prozent der Viewport-Höhe
    sectionvhoffset:
      width: 1/3
      type: toggle
      label: Offset TOP
      when:
        sectionsize: vh
      help: Fügt einen oberen Offset hinzu, z. B. zum Ausgleich eines festen Headers
    sectionflex:
      width: 1/3
      type: select
      label: Section position
      options:
        uk-flex-middle: middle
        uk-flex-bottom: bottom
      when:
        sectionsize: vh
      help: Vertikale Ausrichtung des Inhalts innerhalb der Viewport-Höhe
    sectionremove:
      type: select
      label: Section Padding Remove
      width: 1/2
      options:
        uk-padding-remove-top: top
        uk-padding-remove-bottom: bottom
        uk-padding-remove-vertical: top + bottom
      help: Entfernt gezielt den oberen, unteren oder vertikalen Innenabstand
    sectionbreite:
      type: select
      label: Section Breite
      width: 1/2
      options:
        uk-container-xsmall: xsmall
        uk-container-small: small
        uk-container-large: large
        uk-container-xlarge: xlarge
        uk-container-expand: expand
        remove: remove
      help: Legt die maximale Breite des Inhaltsbereichs innerhalb der Section fest
    sectionexpand:
      type: select
      width: 1/2
      label: zu Seite erweitern
      options:
        uk-container-expand-right: right
        uk-container-expand-left: left
      help: Erweitert die Section zum linken oder rechten Rand des Viewports
    sectionausrichtung:
      type: select
      label: Section Ausrichtung
      width: 1/2
      options:
        uk-flex-middle: middle
        uk-flex-bottom: bottom
      help: Vertikale Ausrichtung des Abschnittinhalts
    flexfirst:
      type: toggle
      width: 1/2
      help: Auf Desktop-Bildschirmen wird das letzte Element im Layout als erstes dargestellt (z. B. für Reihenfolge bei gestapelten Elementen)
    gutter:
      type: select
      label: Gutter
      width: 1/2
      options:
        uk-grid-small: small
        uk-grid-large: large
        uk-grid-collapse: collapse
      help: Abstand (Spacing) zwischen den Grid-Elementen
    sameHeight:
      label: Same Height
      type: toggle
      text: Aktivieren, um gleiche Höhe von Cards zu erzwingen
      help: Aktivieren, um gleiche Höhe aller Elemente innerhalb des Grids zu erzwingen
    toggle_griddivider:
      label: Griddivider
      type: toggle
      width: 1/2
      help: Trennt die Grid-Spalten optisch mit einer Linie
    sectionvisibility:
      label: Section ausblenden/anzeigen ab...
      type: select
      width: 1/2
      options:
        uk-visible@s: ausblenden ab s und größer
        uk-visible@m: ausblenden ab m und größer
        uk-visible@l: ausblenden ab l und größer
        uk-visible@xl: ausblenden ab xl und größer
        uk-hidden@s: anzeigen ab s und kleiner
        uk-hidden@m: anzeigen ab m und kleiner
        uk-hidden@l: anzeigen ab l und kleiner
        uk-hidden@xl: anzeigen ab xl und kleiner
      help: Blendet die Section je nach Bildschirmgröße ein oder aus
    sectiongridchildwidth:
      label: Section Child Width
      type: select
      help: ????Die eingestellte Width hat nur eine Auswirkung auf Layouts kleiner als 1/1
      width: 1/2
      options:
        uk-width-1-2: 1/2
        uk-width-1-3: 1/3
        uk-width-1-4: 1/4
    sectiongridchildwidthresponsiv:
      label: Child Width ab...
      type: select
      width: 1/2
      options:
        s: Child Width ab s bis l
        m: Child Width ab m bis l
      help: ????Legt die Breite der Grid-Elemente ab einer bestimmten Breakpoint-Größe fest
    usebackgroundimage:
      label: Hintergrundbild verwenden
      type: toggle
      text:
        - "Nein"
        - "Ja"
      help: Aktiviert die Verwendung eines Hintergrundbilds für den Abschnitt
    backgroundimage:
      label: Hintergrundbild
      type: files
      multiple: false
      when:
        usebackgroundimage: true
      help: Bilddatei, die als Hintergrundbild der Section verwendet wird
    backgroundimageat:
      label: erst anzeigen ab einer Größe von ...
      type: select
      when:
        usebackgroundimage: true
      options:
        uk-background-image@s: small
        uk-background-image@m: medium
        uk-background-image@l: large
        uk-background-image@xl: xlarge
      help: Zeigt das Hintergrundbild erst ab einer definierten Bildschirmgröße an
    backgroundoptions:
      type: group
      label: Hintergrundbild Optionen
      when:
        usebackgroundimage: true
      fields:
        backgroundsize:
          label: Hintergrundgröße
          type: select
          default: cover
          options:
            contain: "Contain"
            cover: "Cover"
            "": "Originalgröße"
          help: Art der Größenanpassung des Hintergrundbilds (z. B. Cover oder Contain)
        backgroundposition:
          label: Hintergrundposition
          type: select
          options:
            "": "Standard"
            uk-background-top-left: "Oben Links"
            uk-background-top-center: "Oben Mitte"
            uk-background-top-right: "Oben Rechts"
            uk-background-center-left: "Mitte Links"
            uk-background-center-center: "Mitte Mitte"
            uk-background-center-right: "Mitte Rechts"
            uk-background-bottom-left: "Unten Links"
            uk-background-bottom-center: "Unten Mitte"
            uk-background-bottom-right: "Unten Rechts"
          help: Positionierung des Hintergrundbilds innerhalb der Section
        backgroundblendmode:
          label: Hintergrund Blend Mode
          type: select
          options:
            "": "Keiner"
            uk-background-blend-multiply: "Multiply"
            uk-background-blend-screen: "Screen"
            uk-background-blend-overlay: "Overlay"
            uk-background-blend-darken: "Darken"
            uk-background-blend-lighten: "Lighten"
            uk-background-blend-color-dodge: "Color Dodge"
            uk-background-blend-color-burn: "Color Burn"
            uk-background-blend-hard-light: "Hard Light"
            uk-background-blend-soft-light: "Soft Light"
            uk-background-blend-difference: "Difference"
            uk-background-blend-exclusion: "Exclusion"
            uk-background-blend-hue: "Hue"
            uk-background-blend-saturation: "Saturation"
            uk-background-blend-color: "Color"
            uk-background-blend-luminosity: "Luminosity"
          help: Legt einen Mischmodus (Blend Mode) für das Hintergrundbild fest
        backgroundfixed:
          label: Hintergrund fixieren
          type: toggle
          text: false
          help: Fixiert das Hintergrundbild beim Scrollen
