title: Default Page
title: Site
tabs:
  content:
    label: Layout
    columns:
      main:
        width: 1/1
        sections:
          fields:
            type: fields
            fields:
              baselayout: fields/uikit
                                                
  seo: seo/page
  sides:
    label: Unterseiten & Datein
    columns:
      main:
        width: 1/1
        sections:
          pages:
            type: pages
          files:
            type: files