label: Basis Elemente
type: group
fieldsets:
  - heading
  - text
  - list
  - image
  - divider
  - iconflex
  - countup
  - form
  - overlay
  - card
  - panel
  - table
  - social_icons
  - menu_horizontal
  - menu_vertikal
