fields:
  class:
    type: text
    width: 1/2
    help: Zusätzliche CSS-Klassen zur individuellen Gestaltung
  sectioncolor:
    type: select
    label: Section Farbe
    width: 1/2
    options:
      uk-section-primary: primary
      uk-section-secondary: secondary
      uk-section-muted: muted
    help: Bestimmt die Farbstimmung bzw. Hintergrundfarbe des Abschnitts
  sectionsize:
    type: select
    label: Section Padding
    width: 1/2
    options:
      uk-section-xsmall: xsmall
      uk-section-small: small
      uk-section-large: large
      uk-section-xlarge: xlarge
    help: Definiert die vertikale Innenabstände (Padding) der Section
  sectionremove:
    type: select
    label: Section Padding Remove
    width: 1/2
    options:
      uk-padding-remove-top: top
      uk-padding-remove-bottom: bottom
      uk-padding-remove-vertical: top + bottom
    help: Entfernt gezielt den oberen, unteren oder vertikalen Innenabstand
  sectionbreite:
    type: select
    label: Section Breite
    width: 1/2
    options:
      uk-container-xsmall: xsmall
      uk-container-small: small
      uk-container-large: large
      uk-container-xlarge: xlarge
      uk-container-expand: expand
      remove: remove
    help: Legt die maximale Breite des Inhaltsbereichs innerhalb der Section fest
  sectionexpand:
    type: select
    width: 1/2
    label: zu Seite erweitern
    options:
      uk-container-expand-right: right
      uk-container-expand-left: left
    help: Erweitert die Section zum linken oder rechten Rand des Viewports
  sectionausrichtung:
    type: select
    label: Section Ausrichtung Vertikal
    width: 1/2
    options:
      uk-flex-middle: middle
      uk-flex-bottom: bottom
    help: Vertikale Ausrichtung der Section-Inhalte
  sectionausrichtung_hori:
    type: select
    label: Section Ausrichtung Horizontal
    width: 1/2
    options:
      uk-flex-center: center
      uk-flex-right: right
    help: Horizontale Ausrichtung der Section-Inhalte
  gutter:
    type: select
    label: Gutter
    width: 1/2
    options:
      uk-grid-small: small
      uk-grid-large: large
      uk-grid-collapse: collapse
    help: Abstand (Spacing) zwischen den Grid-Elementen
  sameHeight:
    label: Same Height
    type: toggle
    text: Aktivieren, um gleiche Höhe von Cards zu erzwingen
    help: Aktivieren, um gleiche Höhe aller Elemente innerhalb des Grids zu erzwingen
  toggle_griddivider:
    label: Griddivider
    type: toggle
    width: 1/2
    help: Trennt die Grid-Spalten optisch mit einer Linie
  # background image
  usebackgroundimage:
    label: Hintergrundbild verwenden
    type: toggle
    text:
      - "Nein"
      - "Ja"
    help: Aktiviert die Verwendung eines Hintergrundbilds für den Abschnitt
  backgroundimage:
    label: Hintergrundbild
    type: files
    multiple: false
    when:
      usebackgroundimage: true
    help: Bilddatei, die als Hintergrundbild der Section verwendet wird
  backgroundimageat:
    label: erst anzeigen ab einer Größe von ...
    type: select
    when:
      usebackgroundimage: true
    options:
      uk-background-image@s: small
      uk-background-image@m: medium
      uk-background-image@l: large
      uk-background-image@xl: xlarge
    help: Zeigt das Hintergrundbild erst ab einer definierten Bildschirmgröße an
  backgroundoptions:
    type: group
    label: Hintergrundbild Optionen
    when:
      usebackgroundimage: true
    fields:
      backgroundsize:
        label: Hintergrundgröße
        type: select
        default: cover
        options:
          contain: "Contain"
          cover: "Cover"
          "": "Originalgröße"
        help: Art der Größenanpassung des Hintergrundbilds (z. B. Cover oder Contain)
      backgroundposition:
        label: Hintergrundposition
        type: select
        options:
          "": "Standard"
          uk-background-top-left: "Oben Links"
          uk-background-top-center: "Oben Mitte"
          uk-background-top-right: "Oben Rechts"
          uk-background-center-left: "Mitte Links"
          uk-background-center-center: "Mitte Mitte"
          uk-background-center-right: "Mitte Rechts"
          uk-background-bottom-left: "Unten Links"
          uk-background-bottom-center: "Unten Mitte"
          uk-background-bottom-right: "Unten Rechts"
        help: Positionierung des Hintergrundbilds innerhalb der Section
      backgroundblendmode:
        label: Hintergrund Blend Mode
        type: select
        options:
          "": "Keiner"
          uk-background-blend-multiply: "Multiply"
          uk-background-blend-screen: "Screen"
          uk-background-blend-overlay: "Overlay"
          uk-background-blend-darken: "Darken"
          uk-background-blend-lighten: "Lighten"
          uk-background-blend-color-dodge: "Color Dodge"
          uk-background-blend-color-burn: "Color Burn"
          uk-background-blend-hard-light: "Hard Light"
          uk-background-blend-soft-light: "Soft Light"
          uk-background-blend-difference: "Difference"
          uk-background-blend-exclusion: "Exclusion"
          uk-background-blend-hue: "Hue"
          uk-background-blend-saturation: "Saturation"
          uk-background-blend-color: "Color"
          uk-background-blend-luminosity: "Luminosity"
        help: Legt einen Mischmodus (Blend Mode) für das Hintergrundbild fest
      backgroundfixed:
        label: Hintergrund fixieren
        type: toggle
        text: false
        help: Fixiert das Hintergrundbild beim Scrollen
